#!/bin/bash -efu

cwd="${0%/*}"

cat >"$cwd/Makefile" <<EOF
include $PWD/.build/dest/usr/share/mkinitrd/mk/functions.mk

FEATURESDIR = $cwd
EOF

cat >>"$cwd/Makefile" <<'EOF'

$(call include-feature,aaa,aaa/rules.mk)
$(call include-feature,aaa,aaa/rules.mk)
$(call include-feature,aaa,aaa/rules.mk)

all:
	@:
EOF

make --no-print-directory -C "$cwd"
rm -f -- "$cwd/Makefile"
